# Generated by Django 4.1.5 on 2023-01-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=5, null=True)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=500)),
                ('insight', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('start_year', models.CharField(max_length=500, null=True)),
                ('impact', models.CharField(max_length=500, null=True)),
                ('added', models.CharField(max_length=500)),
                ('published', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('likelihood', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='json/')),
                ('data', models.JSONField()),
            ],
        ),
    ]
