# Generated by Django 4.1.5 on 2023-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
