# Generated by Django 4.1.5 on 2023-01-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_alter_jsondata_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
    ]
